# Generated by Django 4.1.3 on 2022-11-28 22:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CA_Zip',
            fields=[
                ('zip_code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('state', models.CharField(default='CA', max_length=2)),
                ('county', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.PositiveSmallIntegerField(help_text='Student ID', primary_key=True, serialize=False)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('D', 'DRIVER'), ('P', 'PASSENGER'), ('E', 'EITHER')], max_length=9)),
                ('seats', models.PositiveSmallIntegerField(help_text='Available seats')),
                ('gender', models.CharField(choices=[('F', 'FEMALE'), ('M', 'MALE'), ('N', 'NON-BINARY')], max_length=6)),
                ('under_25', models.PositiveSmallIntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')])),
                ('undergrad', models.PositiveSmallIntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')])),
                ('smoker', models.PositiveSmallIntegerField(choices=[(0, 'FALSE'), (1, 'TRUE')])),
                ('college', models.CharField(choices=[('COBA', 'COBA'), ('CSTEM', 'CSTEM'), ('CEHHS', 'CEHHS'), ('CHABSS', 'CHABSS'), ('UNDECLARED', 'UNDECLARED')], max_length=10)),
                ('pref_gender', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'FALSE'), (1, 'TRUE')], null=True, verbose_name='Prefer same gender?')),
                ('pref_age', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'FALSE'), (1, 'TRUE')], null=True, verbose_name='Prefer same age group?')),
                ('pref_status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'FALSE'), (1, 'TRUE')], null=True, verbose_name='Prefer same school status? (Undergrad/Grad)')),
                ('pref_nonsmoker', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'FALSE'), (1, 'TRUE')], null=True, verbose_name='Prefer non-smoker?')),
                ('M_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Monday Arrival')),
                ('M_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Monday Departure')),
                ('T_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Tuesday Arrival')),
                ('T_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Tuesday Departure')),
                ('W_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Wednesday Arrival')),
                ('W_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Wednesday Departure')),
                ('R_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Thursday Arrival')),
                ('R_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Thursday Departure')),
                ('F_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Friday Arrival')),
                ('F_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Friday Departure')),
                ('S_arr', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Saturday Arrival')),
                ('S_dep', models.TimeField(blank=True, choices=[(None, '------'), (datetime.time(7, 0), '07:00'), (datetime.time(8, 0), '08:00'), (datetime.time(9, 0), '09:00'), (datetime.time(10, 0), '10:00'), (datetime.time(11, 0), '11:00'), (datetime.time(12, 0), '12:00'), (datetime.time(13, 0), '13:00'), (datetime.time(14, 0), '14:00'), (datetime.time(15, 0), '15:00'), (datetime.time(16, 0), '16:00'), (datetime.time(17, 0), '17:00'), (datetime.time(18, 0), '18:00'), (datetime.time(19, 0), '19:00'), (datetime.time(20, 0), '20:00'), (datetime.time(21, 0), '21:00'), (datetime.time(22, 0), '22:00')], null=True, verbose_name='Saturday Departure')),
            ],
        ),
        migrations.CreateModel(
            name='Carpools',
            fields=[
                ('carpool_id', models.AutoField(primary_key=True, serialize=False)),
                ('driver_id', models.PositiveSmallIntegerField()),
                ('passenger_1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_1', models.CharField(blank=True, max_length=3, null=True)),
                ('schedule_1', models.CharField(blank=True, choices=[('week', 'MTWRFS'), ('MWF', 'MWF'), ('TR', 'TR'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('S', 'S')], max_length=10, null=True)),
                ('passenger_2', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_2', models.CharField(blank=True, max_length=3, null=True)),
                ('schedule_2', models.CharField(blank=True, choices=[('week', 'MTWRFS'), ('MWF', 'MWF'), ('TR', 'TR'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('S', 'S')], max_length=10, null=True)),
                ('passenger_3', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('score_3', models.CharField(blank=True, max_length=3, null=True)),
                ('schedule_3', models.CharField(blank=True, choices=[('week', 'MTWRFS'), ('MWF', 'MWF'), ('TR', 'TR'), ('M', 'M'), ('T', 'T'), ('W', 'W'), ('R', 'R'), ('F', 'F'), ('S', 'S')], max_length=10, null=True)),
                ('direction', models.CharField(choices=[('RT', 'round-trip'), ('O', 'outbound'), ('R', 'return')], default='RT', max_length=10)),
                ('create_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation Date')),
            ],
        ),
        migrations.CreateModel(
            name='ParkRide',
            fields=[
                ('lot_id', models.IntegerField(primary_key=True, serialize=False)),
                ('zip_code', models.PositiveSmallIntegerField()),
                ('district', models.CharField(max_length=3)),
                ('county', models.CharField(max_length=3)),
                ('city', models.CharField(max_length=22)),
                ('name', models.CharField(max_length=60)),
                ('address', models.CharField(max_length=120)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('origin_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('s_route_dist', models.TextField()),
                ('s_route_time', models.TextField()),
                ('travel_time', models.CharField(max_length=10)),
                ('travel_distance', models.DecimalField(decimal_places=2, max_digits=7)),
                ('zips_on_route', models.CharField(max_length=4000)),
            ],
        ),
    ]
